const game = [
    {
        "name":"贪玩蓝月-安卓包",
        "top":"12",
        "game":[
            {
                "game_name":"传奇来了:(196)",
                "game_id":"196",
                "game_byname":"cqll"
            },
            {
                "game_name":"炼狱传奇:(165)",
                "game_id":"165",
                "game_byname":"lianycq"
            },
            {
                "game_name":"贪玩蓝月-古天乐:(190)",
                "game_id":"190",
                "game_byname":"wzcqgtl"
            },
            {
                "game_name":"贪玩蓝月-孙红雷:(191)",
                "game_id":"191",
                "game_byname":"wzcqshl"
            },
            {
                "game_name":"贪玩蓝月-应用宝:(238)",
                "game_id":"238",
                "game_byname":"twly"
            },
            {
                "game_name":"贪玩蓝月-张家辉:(197)",
                "game_id":"197",
                "game_byname":"wzcqzjh"
            },
            {
                "game_name":"贪玩蓝月-戒指:(156)",
                "game_id":"156",
                "game_byname":"wzcq"
            },
            {
                "game_name":"贪玩蓝月-王者传奇:(231)",
                "game_id":"231",
                "game_byname":"wzcqcq"
            },
            {
                "game_name":"贪玩蓝月-陈小春:(324)",
                "game_id":"324",
                "game_byname":"AllANT"
            }
        ]
    },
    {
        "name":"贪玩蓝月-iOS包",
        "top":"11",
        "game":[
            {
                "game_name":"传奇来了(IOS):(182)",
                "game_id":"182",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"剑指沙城(IOS):(212)",
                "game_id":"212",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"屠龙传说(IOS):(211)",
                "game_id":"211",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"格斗无双之主宰龙城(IOS):(344)",
                "game_id":"344",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"炼狱传奇(IOS):(164)",
                "game_id":"164",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"烈火裁决(IOS):(271)",
                "game_id":"271",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"独霸沙城(IOS):(169)",
                "game_id":"169",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"王者传奇online(IOS):(175)",
                "game_id":"175",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"盛世沙城(IOS):(279)",
                "game_id":"279",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩屠龙(IOS):(269)",
                "game_id":"269",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩狼月(IOS):(272)",
                "game_id":"272",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月-复刻版(IOS):(303)",
                "game_id":"303",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月-屠龙决战(IOS):(153)",
                "game_id":"153",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月-张家辉(IOS):(185)",
                "game_id":"185",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月-戒指-纯传奇(IOS):(186)",
                "game_id":"186",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月-贪狼蓝月(IOS):(299)",
                "game_id":"299",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月2-戒指-原版(IOS)(IOS):(217)",
                "game_id":"217",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月HD(IOS):(270)",
                "game_id":"270",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月OL(IOS):(378)",
                "game_id":"378",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月Online(IOS):(360)",
                "game_id":"360",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月热血版(IOS):(234)",
                "game_id":"234",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月特别版(IOS):(368)",
                "game_id":"368",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月美国账号(IOS):(367)",
                "game_id":"367",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩蓝月重制版(IOS):(328)",
                "game_id":"328",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"贪玩霸业(IOS):(183)",
                "game_id":"183",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"醉卧沙城(IOS):(347)",
                "game_id":"347",
                "game_byname":"AllIOS"
            },
            {
                "game_name":"龙城王者(IOS):(184)",
                "game_id":"184",
                "game_byname":"AllIOS"
            }
        ]
    }   
]
export default game